INSERT INTO goods_analysis(datetime,name,total_count,total_people,sum_price,single_people,single_price,more_people,more_price,single_price_rate,more_price_rate,name_morning,morning_count,morning_people,morning_price,single_people_morning,single_price_morning,more_people_morning,more_price_morning,single_price_rate_morning,more_price_rate_morning,name_afternoon,afternoon_count,afternoon_people,afternoon_price,single_people_afternoon,single_price_afternoon,more_people_afternoon,more_price_afternoon,single_price_rate_afternoon,more_price_rate_afternoon)
VALUES(
CURRENT_DATE,
"总盘", 
(SELECT COUNT(1) FROM goods),
(SELECT COUNT(1) FROM ( SELECT DISTINCT belong,nickname FROM goods) AS aa),
(SELECT SUM(price) FROM goods),
(SELECT COUNT(*) FROM ( SELECT belong, nickname, COUNT(*) AS num, price, create_time FROM goods GROUP BY belong having num < 2) AS aa),
(SELECT SUM(price) FROM goods WHERE belong in (SELECT belong FROM (SELECT belong, COUNT(*) AS num, price, create_time FROM goods GROUP BY belong having num < 2) AS cc)),
(SELECT COUNT(*) FROM (SELECT belong, COUNT(*) AS num, price, create_time FROM goods GROUP BY belong having num >= 2) AS dd),
(SELECT SUM(price) FROM goods WHERE belong in (SELECT belong FROM (SELECT belong, COUNT(*) AS num, price, create_time FROM goods GROUP BY belong having num >= 2) AS ee)),
(SELECT (SELECT SUM(price) FROM goods WHERE belong in (SELECT belong FROM (SELECT belong, COUNT(*) AS num, price, create_time FROM goods GROUP BY belong having num < 2) AS ff))/(SELECT SUM( price) FROM goods)),
(SELECT (SELECT SUM(price) FROM goods WHERE belong in (SELECT belong FROM (SELECT belong, COUNT(*) AS num, price, create_time FROM goods GROUP BY belong having num >= 2) AS gg))/(SELECT SUM( price) FROM goods)),
"上午场",
(SELECT COUNT(1) FROM goods WHERE sid = 1),
(SELECT COUNT(1) FROM ( SELECT DISTINCT belong,nickname FROM goods WHERE sid = 1) AS hh),
(SELECT SUM(price) FROM goods WHERE sid = 1),
(SELECT COUNT(*) FROM ( SELECT belong, nickname, COUNT(*) AS num, price, create_time FROM goods WHERE sid = 1 GROUP BY belong having num < 2) AS ii),
(SELECT SUM(price) FROM goods WHERE sid = 1 AND belong in (SELECT belong FROM (SELECT belong, COUNT(*) AS num, price, create_time FROM goods WHERE sid = 1 GROUP BY belong having num < 2) AS jj)),
(SELECT COUNT(*) FROM (SELECT belong, COUNT(*) AS num, price, create_time FROM goods WHERE sid = 1 GROUP BY belong having num >= 2) AS kk),
(SELECT SUM(price) FROM goods WHERE sid = 1 AND belong in (SELECT belong FROM (SELECT belong, COUNT(*) AS num, price, create_time FROM goods WHERE sid = 1 GROUP BY belong having num >= 2) AS ll)),
(SELECT (SELECT SUM(price) FROM goods WHERE sid = 1 AND belong in (SELECT belong FROM (SELECT belong, COUNT(*) AS num, price, create_time FROM goods WHERE sid = 1 GROUP BY belong having num < 2) AS mm))/(SELECT SUM(price) FROM goods WHERE sid = 1)),
(SELECT (SELECT SUM(price) FROM goods WHERE sid = 1 AND belong in (SELECT belong FROM (SELECT belong, COUNT(*) AS num, price, create_time FROM goods WHERE sid = 1 GROUP BY belong having num >= 2) AS nn))/(SELECT SUM(price) FROM goods WHERE sid = 1)),
"下午场",
(SELECT COUNT(1) FROM goods WHERE sid = 9),
(SELECT COUNT(1) FROM ( SELECT DISTINCT belong,nickname FROM goods WHERE sid = 9) AS oo),
(SELECT SUM(price) FROM goods WHERE sid = 9),
(SELECT COUNT(*) FROM ( SELECT belong, nickname, COUNT(*) AS num, price, create_time FROM goods WHERE sid = 1 GROUP BY belong having num < 2) AS pp),
(SELECT SUM(price) FROM goods WHERE sid = 9 AND belong in (SELECT belong FROM (SELECT belong, COUNT(*) AS num, price, create_time FROM goods WHERE sid = 9 GROUP BY belong having num < 2) AS qq)),
(SELECT COUNT(*) FROM (SELECT belong, COUNT(*) AS num, price, create_time FROM goods WHERE sid = 9 GROUP BY belong having num >= 2) AS rr),
(SELECT SUM(price) FROM goods WHERE sid = 9 AND belong in (SELECT belong FROM (SELECT belong, COUNT(*) AS num, price, create_time FROM goods WHERE sid = 9 GROUP BY belong having num >= 2) AS ss)),
(SELECT (SELECT SUM(price) FROM goods WHERE sid = 9 AND belong in (SELECT belong FROM (SELECT belong, COUNT(*) AS num, price, create_time FROM goods WHERE sid = 9 GROUP BY belong having num < 2) AS tt))/(SELECT SUM(price) FROM goods WHERE sid = 9)),
(SELECT (SELECT SUM(price) FROM goods WHERE sid = 9 AND belong in (SELECT belong FROM (SELECT belong, COUNT(*) AS num, price, create_time FROM goods WHERE sid = 9 GROUP BY belong having num >= 2) AS uu))/(SELECT SUM(price) FROM goods WHERE sid = 9))
);